# Addictol Fallout 4 plugin settings (paste into Addictol.ini)

[Patches]
bThreads=false
bLibDeflate=true
bLoadScreen=false
bProfile=false
bAchievements=true
bFacegen=true
bMemoryManager=true
bSmallBlockAllocator=true
bScaleformAllocator=false
bBSMTAManager=false
bBSPreCulledObjects=false
bINISettingCollection=true
bArchiveLimits=true
bInputSwitch=false
bFasterWorkshop=true
bSaveAddedSoundCategories=false
bCOMInit=true

[Fixes]
bGreyMovie=true
bPackageAllocateLocation=true
bInitTints=true
bLODDistance=true
bActorIsHostileToActor=true
bBGSAIWorldLocationRefRadius=true
bSafeExit=true
bUnalignedLoad=true
bCellInit=true
bWorkbenchSwap=true
nMaxStdIO=-1
bMovementPlanner=true
bEscapeFreeze=true
bIOCacher=true
bTESObjectREFRGetEncounterZone=true
bPipBoyLightInv=true
bInteriorNavCut=false
bMagicEffectApplyEvent=true
bEncounterZoneReset=true
bLeveledListCrash=true
bBakaMaxPapyrusOps=true
bPapyrusGCBug=true
bCreateD3DAndSwapchain=true
bCheckInternetAccess=true
bStolenPowerArmorOwnership=true
bManyItems=true
bCombatMusic=true
bWorkbenchSound=true
bActorCauseSaveBloat=true
bUtilityShader=true

[Warnings]
bImageSpaceAdapter=true
bDuplicateAddonNodeIndex=true

[Additional]
bDbgFacegenOutput=false
bUseNewRedistributable=false
uScaleformPageSize=128
uScaleformHeapSize=256
nSleepTimer=125
nMaxLockCount=8
bInteriorNavCutMultiThreading=false
nMaxPapyrusOpsPerFrame=300
bIgnorePreInstallBias=false
nQuitGameDelayMs=1000

[Profiler]
bProfiler=false
bESPProfiler=true
bESPSubHooks=false
bDLLProfiler=true
bModuleProfiler=true
bStartupTimeline=true
bMemoryTracking=true
bBA2Timing=false
bCSVExport=true
